### ISSUE TITLE
Script cannot load using Vite

### ISSUE THREAD

**Issue by lomotech** [studio1902/statamic-peak#326] opened 2023-07-05 00:53 UTC
**Describe the bug**
Clean statamic + peak starter pack cannot load correctly using Vite

**To Reproduce**
1. Create clean project ```statamic new mysite studio1902/statamic-peak```
2. Link it with valet link & valet secure
3. Update .env to put https at APP_URL
4. run ```vite```
5. Script will not load correctly due to some error

**Expected behavior**
Site can load normally. If im not using peak starter pack it will work normally.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser Firefox developer
 - Version 115

**Additional context**
-

**Comment by marcorieser** [comment] 2023-07-05 04:10
Could you please share some more information about "some error" (a bit unspecific) and about how your setup (valet, docker, mamp,...) looks like?

**Comment by marcorieser** [comment] 2023-07-05 04:58
Sorry, dumb question regarding the setup. You mentioned valet. Will have a look.

**Comment by marcorieser** [comment] 2023-07-05 06:42
Went trough the steps to reproduce but everything works fine in Chrome. Firefox throws some errors regarding the SSL certificate but you can manually allow the connection (once for the site itself and once for the Vite dev server connection):

<img width="1149" alt="Bildschirmfoto 2023-07-05 um 08 36 06" src="https://github.com/studio1902/statamic-peak/assets/2395800/484f6da5-25e2-4077-89df-c1d02d47dd70">
<img width="1149" alt="Bildschirmfoto 2023-07-05 um 08 36 16" src="https://github.com/studio1902/statamic-peak/assets/2395800/fedf260b-9ec0-4c74-b0cb-afa150bf6a89">
<img width="1149" alt="Bildschirmfoto 2023-07-05 um 08 36 42" src="https://github.com/studio1902/statamic-peak/assets/2395800/0c6a95e4-24dc-4811-bb7d-1b742e67c687">
<img width="1149" alt="Bildschirmfoto 2023-07-05 um 08 36 50" src="https://github.com/studio1902/statamic-peak/assets/2395800/d4fb9a27-0153-4242-924c-d60cbd079cf8">

**Comment by robdekort** [comment] 2023-07-05 06:56
Thanks Marco! Closing for now.

**Closed by robdekort** 2023-07-05 06:56 UTC
