### ISSUE TITLE
[FR] Translated Version of Peak

### ISSUE THREAD

**Issue by marcorieser** [studio1902/statamic-peak#131] opened 2021-09-24 02:33 UTC
My customers would like to have the control panel set up mostly in German. I would like to use Peak as a starting point but unfortunately it is not yet possible to translate the display names of the fields. As a consequence, I go through all the display names manually in the editor and insert the German translation. So that I don't have to do this over and over again, and so that other people can possibly start with a translated version of Peak, I came up with the following approaches:

- Make a fork of the Peak repository, add the translations there after each update of Peak, and offer a translated version as a separate starter kit.
- A kind of CLI command that runs a search/replace party after installing Peak based on a defined directory structure (e.g. resources/blueprints, resources/fieldsets). This approach could also be used for other starter kits.

I would be happy to look into something like this, but would appreciate some brainstorming since Peak is your project.

**Comment by jelleroorda** [comment] 2021-09-24 07:14
Making a command or bash script that goes in does the replacements sound like the sanest approach to me while displays can not be translated. Keeping another starter kit in sync is **a lot** of work and I wouldn’t recommend it.

**Comment by robdekort** [comment] 2021-09-24 07:38
Hey Marco,

Thank you. Yes this is an omission at the moment. Like you say the issue is that Statamic doesn't support this yet. Funnily enough I translated the whole CP to Dutch (and maintain it) but I never use it since Peak is English. Luckily my clients don't mind. 

I'd love it if you'd thumbs up this FR: https://github.com/statamic/ideas/issues/50. It's the third most request FR so I hope this will get some love soon. 

If you decide to translate Peak I'd be very happy to merge the translations in as soon as we can. If you wanna work on a CLI command to automate this that's also welcome. Peak could ship with duplicate translated yaml files that simply get overwritten. It would be up to the community to keep translations up to date however. 

In the meantime I'd fork Peak, translate it - _maintain that_ - and use the `--local` option with the Statamic CLI to install your own repository as a Starter Kit. 

Hope this helps. Thank you.

**Comment by robdekort** [comment] 2021-09-26 19:08
Closing this for now. Let me know if you wanna do something @marcorieser. I’m up for it. Thanks!

**Closed by robdekort** 2021-09-26 19:08 UTC
Labels: enhancement

**Comment by robdekort** [comment] 2021-10-05 15:39
Hi @marcorieser I spoke with Jack and Jason about this and they're planning this feature. So that's great news.

**Comment by marcorieser** [comment] 2021-10-05 16:54
@robdekort that's awesome! I didn't have the time to put more thoughts into this since then but seems it will not be necessary, perfect.

**Comment by robdekort** [comment] 2021-10-05 16:56
No worries. There's no ETA. But it's coming.
